### ISSUE TITLE
Adyen HPP Deprecation

### ISSUE THREAD

**Issue by TomSearle** [Ucommercenet/UCommerce.Transactions.Payments#32]
We received an email from Adyen announcing that the HPP integration used by uCommerce is being deprecated this year (October 2022). Is there anything on the cards to update the Adyen payment provider to use one of the newer payment methods?

[Information about the deprecation](https://docs.adyen.com/online-payments/classic-integrations/hosted-payment-pages/deprecation)

**Comment by Monrad-UCommerce** [comment]
Dear @TomSearle,

Sorry for the late reply. If you are not getting any replies in this channel please reach out to our support team they will be happy to help you (support@ucommerce.dk).

The team has triaged this, and a sales manager will contact you to help you with the best possible solution.

Best regards
Mads, Lead Developer
