### ISSUE TITLE
Feature: add support for Stripe

### ISSUE THREAD

**Issue by jamiehowarth0** [Ucommercenet/UCommerce.Transactions.Payments#7]
As it says on the tin.

**Comment by mufoxe** [comment]
We are definitely open to PRs 😄

**Comment by jamiehowarth0** [comment]
There's a reason I forked the project 😉

**Comment by mufoxe** [comment]
Lovely! Do let us know if you pointers for the integration. Customer success is always happy to help 😃

**Comment by jamiehowarth0** [comment]
@mufoxe yes please - I'm using the ExternalPaymentService base class and I've got just a couple of q's, if you could jump on a call?

**Comment by jamiehowarth0** [comment]
See #9 for full implementation, compliant with SCA regulations and using Stripe's PaymentIntent API.
